[package]
name = "allan-security-desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
allan-core = { path = "../../crates/core" }
eframe.workspace = true
egui.workspace = true
rfd.workspace = true
serde_json.workspace = true
